/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/movewidgetwithinteractions_screen/MoveWidgetWithInteractionsViewBase.hpp>
#include <touchgfx/canvas_widget_renderer/CanvasWidgetRenderer.hpp>
#include <touchgfx/Color.hpp>
#include <images/BitmapDatabase.hpp>

MoveWidgetWithInteractionsViewBase::MoveWidgetWithInteractionsViewBase() :
    flexButtonCallback(this, &MoveWidgetWithInteractionsViewBase::flexButtonCallbackHandler),
    i_WhiteEndedCallback(this, &MoveWidgetWithInteractionsViewBase::i_WhiteEndedCallbackHandler),
    i_MagentaEndedCallback(this, &MoveWidgetWithInteractionsViewBase::i_MagentaEndedCallbackHandler)
{
    touchgfx::CanvasWidgetRenderer::setupBuffer(canvasBuffer, CANVAS_BUFFER_SIZE);

    __background.setPosition(0, 0, 480, 272);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    scalableImage1.setBitmap(touchgfx::Bitmap(BITMAP_GLASS_THEME_IMAGES_BACKGROUNDS_480X272_CIRCLE_LIGHTS_ID));
    scalableImage1.setPosition(0, 0, 480, 272);
    scalableImage1.setScalingAlgorithm(touchgfx::ScalableImage::NEAREST_NEIGHBOR);
    add(scalableImage1);

    whiteBall.setPosition(80, 96, 80, 80);
    whiteBall.setCenter(40, 40);
    whiteBall.setRadius(20);
    whiteBall.setLineWidth(0);
    whiteBall.setArc(0, 360);
    whiteBallPainter.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    whiteBall.setPainter(whiteBallPainter);
    add(whiteBall);

    magentaBall.setPosition(277, 96, 80, 80);
    magentaBall.setCenter(40, 40);
    magentaBall.setRadius(20);
    magentaBall.setLineWidth(0);
    magentaBall.setArc(0, 360);
    magentaBallPainter.setColor(touchgfx::Color::getColorFromRGB(240, 12, 107));
    magentaBall.setPainter(magentaBallPainter);
    add(magentaBall);

    yellowBall.setPosition(326, 75, 80, 80);
    yellowBall.setCenter(40, 40);
    yellowBall.setRadius(20);
    yellowBall.setLineWidth(0);
    yellowBall.setArc(0, 360);
    yellowBallPainter.setColor(touchgfx::Color::getColorFromRGB(240, 240, 12));
    yellowBall.setPainter(yellowBallPainter);
    add(yellowBall);

    lightBlueBall.setPosition(326, 126, 80, 80);
    lightBlueBall.setCenter(40, 40);
    lightBlueBall.setRadius(20);
    lightBlueBall.setLineWidth(0);
    lightBlueBall.setArc(0, 360);
    lightBlueBallPainter.setColor(touchgfx::Color::getColorFromRGB(12, 216, 235));
    lightBlueBall.setPainter(lightBlueBallPainter);
    add(lightBlueBall);

    purpleBall.setPosition(377, 46, 80, 80);
    purpleBall.setCenter(40, 40);
    purpleBall.setRadius(20);
    purpleBall.setLineWidth(0);
    purpleBall.setArc(0, 360);
    purpleBallPainter.setColor(touchgfx::Color::getColorFromRGB(201, 7, 240));
    purpleBall.setPainter(purpleBallPainter);
    add(purpleBall);

    orangeBall.setPosition(377, 96, 80, 80);
    orangeBall.setCenter(40, 40);
    orangeBall.setRadius(20);
    orangeBall.setLineWidth(0);
    orangeBall.setArc(0, 360);
    orangeBallPainter.setColor(touchgfx::Color::getColorFromRGB(245, 110, 7));
    orangeBall.setPainter(orangeBallPainter);
    add(orangeBall);

    greenBall.setPosition(377, 147, 80, 80);
    greenBall.setCenter(40, 40);
    greenBall.setRadius(20);
    greenBall.setLineWidth(0);
    greenBall.setArc(0, 360);
    greenBallPainter.setColor(touchgfx::Color::getColorFromRGB(19, 222, 16));
    greenBall.setPainter(greenBallPainter);
    add(greenBall);

    flexButton1.setBoxWithBorderPosition(0, 0, 0, 0);
    flexButton1.setBorderSize(5);
    flexButton1.setBoxWithBorderColors(touchgfx::Color::getColorFromRGB(0, 102, 153), touchgfx::Color::getColorFromRGB(0, 153, 204), touchgfx::Color::getColorFromRGB(0, 51, 102), touchgfx::Color::getColorFromRGB(51, 102, 153));
    flexButton1.setAction(flexButtonCallback);
    flexButton1.setPosition(80, 96, 80, 80);
    add(flexButton1);
}

MoveWidgetWithInteractionsViewBase::~MoveWidgetWithInteractionsViewBase()
{
    touchgfx::CanvasWidgetRenderer::resetBuffer();
}

void MoveWidgetWithInteractionsViewBase::setupScreen()
{

}

void MoveWidgetWithInteractionsViewBase::flexButtonCallbackHandler(const touchgfx::AbstractButtonContainer& src)
{
    if (&src == &flexButton1)
    {
        //I_White
        //When flexButton1 clicked move whiteBall
        //Move whiteBall to x:237, y:96 with LinearIn easing in 200 ms (12 Ticks)
        whiteBall.clearMoveAnimationEndedAction();
        whiteBall.startMoveAnimation(237, 96, 12, touchgfx::EasingEquations::linearEaseIn, touchgfx::EasingEquations::linearEaseIn);
        whiteBall.setMoveAnimationEndedAction(i_WhiteEndedCallback);
    }
}

void MoveWidgetWithInteractionsViewBase::i_WhiteEndedCallbackHandler(const touchgfx::MoveAnimator<touchgfx::Circle>& comp)
{
    //I_Purple
    //When I_White completed move purpleBall
    //Move purpleBall to x:406, y:-13 with BounceOut easing in 200 ms (12 Ticks)
    purpleBall.clearMoveAnimationEndedAction();
    purpleBall.startMoveAnimation(406, -13, 12, touchgfx::EasingEquations::bounceEaseOut, touchgfx::EasingEquations::bounceEaseOut);


    //I_Orange
    //When I_White completed move orangeBall
    //Move orangeBall to x:417, y:136 with LinearIn easing in 200 ms (12 Ticks)
    orangeBall.clearMoveAnimationEndedAction();
    orangeBall.startMoveAnimation(417, 136, 12, touchgfx::EasingEquations::linearEaseIn, touchgfx::EasingEquations::linearEaseIn);


    //I_Green
    //When I_White completed move greenBall
    //Move greenBall to x:337, y:206 with BounceIn easing in 200 ms (12 Ticks)
    greenBall.clearMoveAnimationEndedAction();
    greenBall.startMoveAnimation(337, 206, 12, touchgfx::EasingEquations::bounceEaseIn, touchgfx::EasingEquations::bounceEaseIn);


    //I_yellow
    //When I_White completed move yellowBall
    //Move yellowBall to x:259, y:-13 with LinearIn easing in 300 ms (18 Ticks)
    yellowBall.clearMoveAnimationEndedAction();
    yellowBall.startMoveAnimation(259, -13, 18, touchgfx::EasingEquations::linearEaseIn, touchgfx::EasingEquations::linearEaseIn);


    //I_LightBlue
    //When I_White completed move lightBlueBall
    //Move lightBlueBall to x:0, y:0 with LinearIn easing in 300 ms (18 Ticks)
    lightBlueBall.clearMoveAnimationEndedAction();
    lightBlueBall.startMoveAnimation(0, 0, 18, touchgfx::EasingEquations::linearEaseIn, touchgfx::EasingEquations::linearEaseIn);


    //I_Magenta
    //When I_White completed move magentaBall
    //Move magentaBall to x:417, y:96 with BounceOut easing in 200 ms (12 Ticks)
    magentaBall.clearMoveAnimationEndedAction();
    magentaBall.startMoveAnimation(417, 96, 12, touchgfx::EasingEquations::bounceEaseOut, touchgfx::EasingEquations::bounceEaseOut);
    magentaBall.setMoveAnimationEndedAction(i_MagentaEndedCallback);

}

void MoveWidgetWithInteractionsViewBase::i_MagentaEndedCallbackHandler(const touchgfx::MoveAnimator<touchgfx::Circle>& comp)
{
    //I_MagentaBack
    //When I_Magenta completed move magentaBall
    //Move magentaBall to x:277, y:96 with BounceOut easing in 200 ms (12 Ticks)
    magentaBall.clearMoveAnimationEndedAction();
    magentaBall.startMoveAnimation(277, 96, 12, touchgfx::EasingEquations::bounceEaseOut, touchgfx::EasingEquations::bounceEaseOut);

}
