/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/piechartfullcircle_screen/pieChartFullCircleViewBase.hpp>
#include <touchgfx/canvas_widget_renderer/CanvasWidgetRenderer.hpp>
#include <touchgfx/Color.hpp>
#include <images/BitmapDatabase.hpp>

pieChartFullCircleViewBase::pieChartFullCircleViewBase()
{
    touchgfx::CanvasWidgetRenderer::setupBuffer(canvasBuffer, CANVAS_BUFFER_SIZE);

    __background.setPosition(0, 0, 480, 272);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    background.setBitmap(touchgfx::Bitmap(BITMAP_DARK_THEME_IMAGES_BACKGROUNDS_480X272_CARBON_ID));
    background.setPosition(0, 0, 480, 272);
    background.setScalingAlgorithm(touchgfx::ScalableImage::NEAREST_NEIGHBOR);
    add(background);

    pieChartContainer.setPosition(115, 11, 250, 250);
    Serie1.setPosition(0, 0, 240, 240);
    Serie1.setCenter(120, 120);
    Serie1.setRadius(60);
    Serie1.setLineWidth(0);
    Serie1.setArc(90, 130);
    Serie1Painter.setColor(touchgfx::Color::getColorFromRGB(255, 107, 107));
    Serie1.setPainter(Serie1Painter);
    pieChartContainer.add(Serie1);

    Serie2.setPosition(0, 0, 240, 240);
    Serie2.setCenter(120, 120);
    Serie2.setRadius(60);
    Serie2.setLineWidth(0);
    Serie2.setArc(130, 195);
    Serie2Painter.setColor(touchgfx::Color::getColorFromRGB(15, 217, 61));
    Serie2.setPainter(Serie2Painter);
    pieChartContainer.add(Serie2);

    Serie3.setPosition(0, 0, 240, 240);
    Serie3.setCenter(120, 120);
    Serie3.setRadius(60);
    Serie3.setLineWidth(0);
    Serie3.setArc(180, 280);
    Serie3Painter.setColor(touchgfx::Color::getColorFromRGB(237, 199, 74));
    Serie3.setPainter(Serie3Painter);
    pieChartContainer.add(Serie3);

    Serie4.setPosition(0, 0, 240, 240);
    Serie4.setCenter(120, 120);
    Serie4.setRadius(60);
    Serie4.setLineWidth(0);
    Serie4.setArc(280, 350);
    Serie4Painter.setColor(touchgfx::Color::getColorFromRGB(77, 150, 255));
    Serie4.setPainter(Serie4Painter);
    pieChartContainer.add(Serie4);

    Serie5.setPosition(0, 0, 240, 240);
    Serie5.setCenter(120, 120);
    Serie5.setRadius(60);
    Serie5.setLineWidth(0);
    Serie5.setArc(350, 380);
    Serie5Painter.setColor(touchgfx::Color::getColorFromRGB(157, 78, 221));
    Serie5.setPainter(Serie5Painter);
    pieChartContainer.add(Serie5);

    Serie6.setPosition(0, 0, 240, 240);
    Serie6.setCenter(120, 120);
    Serie6.setRadius(60);
    Serie6.setLineWidth(0);
    Serie6.setArc(380, 450);
    Serie6Painter.setColor(touchgfx::Color::getColorFromRGB(243, 139, 160));
    Serie6.setPainter(Serie6Painter);
    pieChartContainer.add(Serie6);

    add(pieChartContainer);

    newPieChartButton.setXY(79, 215);
    newPieChartButton.setBitmaps(touchgfx::Bitmap(BITMAP_DARK_THEME_IMAGES_WIDGETS_BUTTON_ICON_ROUND_MICRO_FILL_NORMAL_ID), touchgfx::Bitmap(BITMAP_DARK_THEME_IMAGES_WIDGETS_BUTTON_ICON_ROUND_MICRO_FILL_PRESSED_ID));
    add(newPieChartButton);
}

pieChartFullCircleViewBase::~pieChartFullCircleViewBase()
{
    touchgfx::CanvasWidgetRenderer::resetBuffer();
}

void pieChartFullCircleViewBase::setupScreen()
{

}
