/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef PIECHARTFULLCIRCLEVIEWBASE_HPP
#define PIECHARTFULLCIRCLEVIEWBASE_HPP

#include <gui/common/FrontendApplication.hpp>
#include <mvp/View.hpp>
#include <gui/piechartfullcircle_screen/pieChartFullCirclePresenter.hpp>
#include <touchgfx/widgets/Box.hpp>
#include <touchgfx/widgets/ScalableImage.hpp>
#include <touchgfx/containers/Container.hpp>
#include <touchgfx/widgets/canvas/Circle.hpp>
#include <touchgfx/widgets/canvas/PainterRGB565.hpp>
#include <touchgfx/widgets/Button.hpp>

class pieChartFullCircleViewBase : public touchgfx::View<pieChartFullCirclePresenter>
{
public:
    pieChartFullCircleViewBase();
    virtual ~pieChartFullCircleViewBase();
    virtual void setupScreen();

protected:
    FrontendApplication& application() {
        return *static_cast<FrontendApplication*>(touchgfx::Application::getInstance());
    }

    /*
     * Member Declarations
     */
    touchgfx::Box __background;
    touchgfx::ScalableImage background;
    touchgfx::Container pieChartContainer;
    touchgfx::Circle Serie1;
    touchgfx::PainterRGB565 Serie1Painter;
    touchgfx::Circle Serie2;
    touchgfx::PainterRGB565 Serie2Painter;
    touchgfx::Circle Serie3;
    touchgfx::PainterRGB565 Serie3Painter;
    touchgfx::Circle Serie4;
    touchgfx::PainterRGB565 Serie4Painter;
    touchgfx::Circle Serie5;
    touchgfx::PainterRGB565 Serie5Painter;
    touchgfx::Circle Serie6;
    touchgfx::PainterRGB565 Serie6Painter;
    touchgfx::Button newPieChartButton;

private:

    /*
     * Canvas Buffer Size
     */
    static const uint32_t CANVAS_BUFFER_SIZE = 7200;
    uint8_t canvasBuffer[CANVAS_BUFFER_SIZE];

};

#endif // PIECHARTFULLCIRCLEVIEWBASE_HPP
