/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/starflexbuttonicon_screen/StarFlexButtonIconViewBase.hpp>
#include <touchgfx/Color.hpp>
#include <images/BitmapDatabase.hpp>
#include <texts/TextKeysAndLanguages.hpp>

StarFlexButtonIconViewBase::StarFlexButtonIconViewBase() :
    flexButtonCallback(this, &StarFlexButtonIconViewBase::flexButtonCallbackHandler)
{
    __background.setPosition(0, 0, 480, 272);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    scalableImage1.setBitmap(touchgfx::Bitmap(BITMAP_BG_BLUE_SALMON_ID));
    scalableImage1.setPosition(0, 0, 480, 272);
    scalableImage1.setScalingAlgorithm(touchgfx::ScalableImage::NEAREST_NEIGHBOR);
    add(scalableImage1);

    container1.setPosition(70, 144, 250, 74);
    add(container1);

    textArea1.setPosition(344, 156, 43, 53);
    textArea1.setColor(touchgfx::Color::getColorFromRGB(247, 250, 250));
    textArea1.setLinespacing(0);
    Unicode::snprintf(textArea1Buffer, TEXTAREA1_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_CQDS).getText());
    textArea1.setWildcard(textArea1Buffer);
    textArea1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_Y4DH));
    add(textArea1);

    textArea1_1.setPosition(90, 96, 124, 57);
    textArea1_1.setColor(touchgfx::Color::getColorFromRGB(247, 250, 250));
    textArea1_1.setLinespacing(0);
    textArea1_1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_X4YO));
    add(textArea1_1);

    star1.setIconBitmaps(Bitmap(BITMAP_ICON_THEME_IMAGES_TOGGLE_STAR_BORDER_50_50_E8F6FB_SVG_ID), Bitmap(BITMAP_ICON_THEME_IMAGES_TOGGLE_STAR_PURPLE500_50_50_EDED18_SVG_ID));
    star1.setIconXY(0, 0);
    star1.setAction(flexButtonCallback);
    star1.setPosition(35, 156, 50, 50);
    add(star1);

    star2.setIconBitmaps(Bitmap(BITMAP_ICON_THEME_IMAGES_TOGGLE_STAR_BORDER_50_50_E8F6FB_SVG_ID), Bitmap(BITMAP_ICON_THEME_IMAGES_TOGGLE_STAR_PURPLE500_50_50_EDED18_SVG_ID));
    star2.setIconXY(0, 0);
    star2.setAction(flexButtonCallback);
    star2.setPosition(85, 156, 50, 50);
    add(star2);

    star3.setIconBitmaps(Bitmap(BITMAP_ICON_THEME_IMAGES_TOGGLE_STAR_BORDER_50_50_E8F6FB_SVG_ID), Bitmap(BITMAP_ICON_THEME_IMAGES_TOGGLE_STAR_PURPLE500_50_50_EDED18_SVG_ID));
    star3.setIconXY(0, 0);
    star3.setAction(flexButtonCallback);
    star3.setPosition(135, 156, 50, 50);
    add(star3);

    star4.setIconBitmaps(Bitmap(BITMAP_ICON_THEME_IMAGES_TOGGLE_STAR_BORDER_50_50_E8F6FB_SVG_ID), Bitmap(BITMAP_ICON_THEME_IMAGES_TOGGLE_STAR_PURPLE500_50_50_EDED18_SVG_ID));
    star4.setIconXY(0, 0);
    star4.setAction(flexButtonCallback);
    star4.setPosition(185, 156, 50, 50);
    add(star4);

    star5.setIconBitmaps(Bitmap(BITMAP_ICON_THEME_IMAGES_TOGGLE_STAR_BORDER_50_50_E8F6FB_SVG_ID), Bitmap(BITMAP_ICON_THEME_IMAGES_TOGGLE_STAR_PURPLE500_50_50_EDED18_SVG_ID));
    star5.setIconXY(0, 0);
    star5.setAction(flexButtonCallback);
    star5.setPosition(235, 156, 50, 50);
    add(star5);
}

StarFlexButtonIconViewBase::~StarFlexButtonIconViewBase()
{

}

void StarFlexButtonIconViewBase::setupScreen()
{

}

void StarFlexButtonIconViewBase::flexButtonCallbackHandler(const touchgfx::AbstractButtonContainer& src)
{
    if (&src == &star1)
    {
        //Interaction1
        //When star1 clicked call virtual function
        //Call updateRating
        updateRating();
    }
    if (&src == &star2)
    {
        //Interaction2
        //When star2 clicked call virtual function
        //Call updateRating
        updateRating();
    }
    if (&src == &star5)
    {
        //Interaction3
        //When star5 clicked call virtual function
        //Call updateRating
        updateRating();
    }
    if (&src == &star4)
    {
        //Interaction4
        //When star4 clicked call virtual function
        //Call updateRating
        updateRating();
    }
    if (&src == &star3)
    {
        //Interaction5
        //When star3 clicked call virtual function
        //Call updateRating
        updateRating();
    }
}
