/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/wirelessicon_screen/WirelessIconViewBase.hpp>
#include <touchgfx/canvas_widget_renderer/CanvasWidgetRenderer.hpp>
#include <touchgfx/Color.hpp>
#include <images/BitmapDatabase.hpp>

WirelessIconViewBase::WirelessIconViewBase()
{
    touchgfx::CanvasWidgetRenderer::setupBuffer(canvasBuffer, CANVAS_BUFFER_SIZE);

    __background.setPosition(0, 0, 480, 272);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    background.setBitmap(touchgfx::Bitmap(BITMAP_BG_GREENGRADIENT_ID));
    background.setPosition(0, 0, 480, 272);
    background.setScalingAlgorithm(touchgfx::ScalableImage::NEAREST_NEIGHBOR);
    add(background);

    circle80.setPosition(278, 110, 160, 160);
    circle80.setCenter(80, 80);
    circle80.setRadius(80);
    circle80.setLineWidth(0);
    circle80.setArc(45, -45);
    circle80Painter.setColor(touchgfx::Color::getColorFromRGB(2, 24, 120));
    circle80.setPainter(circle80Painter);
    circle80.setVisible(false);
    add(circle80);

    circle60.setPosition(278, 110, 160, 160);
    circle60.setCenter(80, 80);
    circle60.setRadius(60);
    circle60.setLineWidth(0);
    circle60.setArc(45, -45);
    circle60Painter.setColor(touchgfx::Color::getColorFromRGB(6, 29, 128));
    circle60.setPainter(circle60Painter);
    circle60.setVisible(false);
    add(circle60);

    circle40.setPosition(278, 110, 160, 160);
    circle40.setCenter(80, 80);
    circle40.setRadius(40);
    circle40.setLineWidth(0);
    circle40.setArc(45, -45);
    circle40Painter.setColor(touchgfx::Color::getColorFromRGB(7, 38, 176));
    circle40.setPainter(circle40Painter);
    circle40.setVisible(false);
    add(circle40);

    circle20.setPosition(278, 110, 160, 160);
    circle20.setCenter(80, 80);
    circle20.setRadius(20);
    circle20.setLineWidth(0);
    circle20.setArc(45, -45);
    circle20Painter.setColor(touchgfx::Color::getColorFromRGB(6, 43, 207));
    circle20.setPainter(circle20Painter);
    circle20.setVisible(false);
    add(circle20);

    circle10.setPosition(278, 110, 160, 160);
    circle10.setCenter(80, 80);
    circle10.setRadius(10);
    circle10.setLineWidth(0);
    circle10.setArc(45, -45);
    circle10Painter.setColor(touchgfx::Color::getColorFromRGB(10, 52, 242));
    circle10.setPainter(circle10Painter);
    circle10.setVisible(false);
    add(circle10);

    toggleButton1.setXY(32, 111);
    toggleButton1.setBitmaps(touchgfx::Bitmap(BITMAP_CLAY_THEME_IMAGES_WIDGETS_TOGGLEBUTTON_MEDIUM_ROUND_TEXT_OFF_NORMAL_ID), touchgfx::Bitmap(BITMAP_CLAY_THEME_IMAGES_WIDGETS_TOGGLEBUTTON_MEDIUM_ROUND_TEXT_ON_DARK_ID));
    add(toggleButton1);
}

WirelessIconViewBase::~WirelessIconViewBase()
{
    touchgfx::CanvasWidgetRenderer::resetBuffer();
}

void WirelessIconViewBase::setupScreen()
{

}
